-- AlterTable
ALTER TABLE "TutorProfile" ADD COLUMN "manualQ1Year" INTEGER,
ADD COLUMN "manualQ1M1Chf" DOUBLE PRECISION,
ADD COLUMN "manualQ1M2Chf" DOUBLE PRECISION,
ADD COLUMN "manualQ1M3Chf" DOUBLE PRECISION;
